SET SERVEROUTPUT ON;

-- Creamos la tabla
CREATE TABLE EMPLEADO(
ID INTEGER PRIMARY KEY,
NOMBRE VARCHAR2(80),
SUELDO_BASE FLOAT);

INSERT INTO EMPLEADO VALUES(1,'Ana',400);
INSERT INTO EMPLEADO VALUES(2,'Juan',350);
INSERT INTO EMPLEADO VALUES(3,'Pedro',600);
INSERT INTO EMPLEADO VALUES(4,'Luis',520);

SELECT * FROM EMPLEADO;

-- Cursor implícito (es una sola ocurrencia)
DECLARE
NUM_EMPLEADOS INTEGER;
BEGIN
-- El siguiente es el cursor
SELECT COUNT(*) INTO NUM_EMPLEADOS FROM EMPLEADO;
IMPRIMIR('Los empleados son '||NUM_EMPLEADOS);
END;
/
