SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE IMPRIMIR(MENSA IN VARCHAR2)
AS
BEGIN
DBMS_OUTPUT.PUT_LINE(MENSA);
END;
/

-- Vamos a invocarlo internamente, es decir desde aquí en Oracle
BEGIN
IMPRIMIR('Vamos a ver si funciona');
END;
/

-- Ejercicio 2
-- a)
CREATE TABLE DANCE(ID INTEGER PRIMARY KEY, MENSAJE VARCHAR2(80));

-- b)
CREATE OR REPLACE PROCEDURE GUARDAR_DANCE(VAL1 IN INTEGER, VAL2 IN VARCHAR2)
AS
BEGIN
INSERT INTO DANCE VALUES(VAL1,VAL2);
END;
/

-- Probamos internamente
BEGIN
GUARDAR_DANCE(1,'Mi primer mensajito');
END;
/

SELECT * FROM DANCE;
