SET SERVEROUTPUT ON;
--Ejercicio #1
CREATE TABLE Sitio_adultos(ID INTEGER PRIMARY KEY,Nombre VARCHAR2(60), Edad INTEGER);
--Generamos un auto-incremento para el ID
CREATE SEQUENCE SEC_AUTO_INCREMENTO
START WITH 5
INCREMENT BY 1
NOMAXVALUE;
--Generamos un Procedimiento de Almacenado 
CREATE OR REPLACE PROCEDURE ALMACENAR_BEFORE(VALOR OUT INTEGER, NOMBRE IN VARCHAR2, EDAD IN INTEGER)
AS
BEGIN
SELECT SEC_AUTO_INCREMENTO.NEXTVAL INTO VALOR FROM DUAL;
INSERT INTO Sitio_adultos VALUES(VALOR,NOMBRE,EDAD);
END;
/
--Generamos el Disparador (Trigger)
CREATE OR REPLACE TRIGGER DISP_ADULTOS BEFORE INSERT ON Sitio_adultos
FOR EACH ROW --Se disparará en cada vuelta
BEGIN
IF :NEW.EDAD<18 THEN
RAISE_APPLICATION_ERROR(-20001,'Lo siento pero estas chavo');--(-20001) Es un código de error (comodín)
END IF;
END;
/
--Lo probamos
SELECT * FROM Sitio_adultos;
DECLARE
VALOR2 INTEGER;
BEGIN
ALMACENAR_BEFORE(VALOR2,'Yiraya',60);
END;
/


