SET SERVEROUTPUT ON;
CREATE TABLE GENERAL_1(ID INTEGER PRIMARY KEY,
NOMBRE VARCHAR2(80),EDAD INTEGER);

CREATE TABLE ESPEJO_MAYORES(ID INTEGER PRIMARY KEY,
NOMBRE VARCHAR2(80),EDAD INTEGER);

CREATE TABLE ESPEJO_MENORES(ID INTEGER PRIMARY KEY,
NOMBRE VARCHAR2(80),EDAD INTEGER);

SELECT * FROM GENERAL_1;

SELECT * FROM ESPEJO_MAYORES;

SELECT * FROM ESPEJO_MENORES;

--CREAMOS DISPARADORES
CREATE OR REPLACE TRIGGER DISP_MAESTRA AFTER INSERT ON GENERAL_1
FOR EACH ROW
BEGIN 
IF :NEW.EDAD>18 THEN
INSERT INTO ESPEJO_MAYORES VALUES(:NEW.ID, :NEW.NOMBRE, :NEW.EDAD);
ELSE
INSERT INTO ESPEJO_MENORES VALUES(:NEW.ID, :NEW.NOMBRE, :NEW.EDAD);
END IF;
END;
/
